### ISSUE TITLE
希望增加自定义OPENAI_API_BASE 的功能

### ISSUE THREAD

**Issue by yefx** [kuafuai/DevOpsGPT#10]

**Comment by booboosui** [comment]
收到

**Comment by dholakashyap** [comment]
are you saying that you want to use azure openai API ??
because in Azure OpenAi we need to add OPENAI_API_BASE

**Comment by booboosui** [comment]
我们已经支持该配置，配置部分调整比较多，您可以重新克隆master代码，重新调整配置文件

相关PR：https://github.com/kuafuai/DevOpsGPT/pull/12   感谢 @bdoycn 贡献的代码

@dholakashyap We already support this configuration, the configuration part of the adjustment is more, you can re-clone the master code, re-adjust the configuration file
