### ISSUE TITLE
GPT KEY is configured. But, log shows "Failed to access GPT" which cause the exception

### ISSUE THREAD

**Issue by xusongfeng** [kuafuai/DevOpsGPT#112]
我在CHATGPT里取到了key
![image](https://github.com/kuafuai/DevOpsGPT/assets/26130192/07c1dcdd-4454-46bb-b405-562c4faf7cb4)

填写配置后， log显示无法连接
![image](https://github.com/kuafuai/DevOpsGPT/assets/26130192/3831a0c3-0206-4c73-a7ef-edb82b9a8f25)

GPT_KEYS: |
    {
        "openai": {
            "keys": [
                {"sk-3xx7McVxx": {"count": 0, "timestamp": 0}}
            ],
            "api_type": "open_ai",
            "api_base": "https://api.openai.com/v1",
            "api_version": "2020-11-07",
            "proxy": "None"
        }
    }

请问是我遗漏了什么配置吗？

**Comment by booboosui** [comment]
看下账单（billing），应该是免费额度过期了，key无法继续使用
