### ISSUE TITLE
报错无法进入webui

### ISSUE THREAD

**Issue by yeyi913** [kuafuai/DevOpsGPT#14]
<img width="863" alt="226dabbd99ab52ea844bba37e697c0e" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/d99f7f48-9dd7-498b-bf16-35d16e0a6e16">
<img width="1280" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/f4cdb35b-5103-42dd-ba0b-286ce7487b43">
<img width="872" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/14703a26-bba3-4a2a-b485-f64d63a9df58">

**Comment by booboosui** [comment]
直接用cmd，运行 python3 backend\run.py 看看，（python3 根据你的实际情况调整，比如 python3.11）

**Comment by booboosui** [comment]
您可以重新克隆一下最新的代码试试看，如果还有问题，可以联系我们哈：https://github.com/kuafuai/DevOpsGPT/blob/master/docs/CONTACT.md
