### ISSUE TITLE
运行服务失败

### ISSUE THREAD

**Issue by zysvadxd48** [kuafuai/DevOpsGPT#16]
执行脚本
![image](https://github.com/kuafuai/DevOpsGPT/assets/120589492/7205e12a-6c90-4c62-8c89-72f411de2ab3)
运行python程序
![image](https://github.com/kuafuai/DevOpsGPT/assets/120589492/7946a37d-7907-4dcf-a0bb-199ae0effd88)
备注：测试key在其他程序中是可用的

**Comment by booboosui** [comment]
直接用cmd，运行 python3 backend\run.py 看看，（python3 根据你的实际情况调整，比如 python3.11）
也可以添加我们wx详细沟通：https://github.com/kuafuai/DevOpsGPT/blob/master/docs/CONTACT.md

**Comment by booboosui** [comment]
您可以克隆下最新的代码试试看，如果还有问题，可以联系我们处理  https://github.com/kuafuai/DevOpsGPT/blob/master/docs/CONTACT.md
