### ISSUE TITLE
服务启动后访问404

### ISSUE THREAD

**Issue by Coder1-Michael** [kuafuai/DevOpsGPT#17]
直接运行run.py访问404
![1691121287752](https://github.com/kuafuai/DevOpsGPT/assets/85927859/d8197af1-f527-48d9-afb5-228714220d10)

**Comment by Coder1-Michael** [comment]
使用run.bat也是访问404

**Comment by Coder1-Michael** [comment]
使用run.bat也是404
![1691121549969](https://github.com/kuafuai/DevOpsGPT/assets/85927859/d263bc8e-8af1-4c14-ab40-0737b3b13b3c)

**Comment by booboosui** [comment]
后端服务不能直接访问，是给前端调用用的，运行run.bat，然后用浏览器访问，前端的默认端口是8080

**Comment by Coder1-Michael** [comment]
> 后端服务不能直接访问，是给前端调用用的，运行run.bat，然后用浏览器访问，前端的默认端口是8080

原来是这样啊，确实可以了，不过现在进去前端页面后没法登陆，能帮我看下吗
