### ISSUE TITLE
报错无法生成Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by yeyi913** [kuafuai/DevOpsGPT#18]
<img width="1280" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/af64ea1c-827b-4553-9217-d8a9a1ccd10a">

**Comment by booboosui** [comment]
可以发一下后台的报错日志，确认下是否正确配置了openai的key以及是否可以访问openai的服务器

**Comment by yeyi913** [comment]
<img width="868" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/99199086-70b8-4e80-937e-8a70b4b3a315">
<img width="857" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/b9f3f68e-94d2-4130-a851-339011bfbb3e">
<img width="1280" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/bfb1cdd5-12aa-41d8-8881-e58669fad750">
<img width="1280" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/35433972-020e-4ef1-8e73-7d75664240db">
<img width="1280" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/113336759/77012c01-3b9e-4891-82f1-3c8a994555a1">

**Comment by booboosui** [comment]
<img width="574" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/139328168/2273b90a-a20f-4a01-870a-f9f39fa6e14b">
看上去是你的key超出限制了，可以到openai的平台上看下账单情况

**Comment by wgj0122** [comment]
![屏幕截图 2023-08-04 150650](https://github.com/kuafuai/DevOpsGPT/assets/68603966/a682f547-8b79-4569-b231-dd9aad11795a)
帮忙看看什么原因呢？

**Comment by wgj0122** [comment]
看起来也是OPEN AI超时，但是我是可以正常访问GPT的

**Comment by booboosui** [comment]
你有配置终端代理么？

**Comment by booboosui** [comment]
可以联系我们沟通哈 https://github.com/kuafuai/DevOpsGPT/blob/master/docs/CONTACT.md
