### ISSUE TITLE
找不到文件 FileNotFoundError: [Errno 2] No translation file found for domain: 'controllers'

### ISSUE THREAD

**Issue by Coder1-Michael** [kuafuai/DevOpsGPT#20]
前端服务报错：找不到文件
![image](https://github.com/kuafuai/DevOpsGPT/assets/85927859/ff7cdea3-703a-4d80-afb4-b9f7b27d54cf)

**Comment by booboosui** [comment]
和用户确认了以下，是 microsoft edge  浏览器 @yakeJiang 辛苦下周测试看下哈

**Comment by yakeJiang** [comment]
看日志像是没有登录呀
