### ISSUE TITLE
我是个15年经验加构师, 我认为你们这项目能成. 

### ISSUE THREAD

**Issue by ybeetle8** [kuafuai/DevOpsGPT#30]
我近几个月一直在使用AI开发,  基本上我80% 以上的开发都已转移到了ai 开发, 但是现有的自动化产品都不能实现我想像的功能, 你们这个非常接近了.  软件开发就是得到中途不断修改模块需求.  

程序员我认为是可以大量替代的, 但加构师很难, 因为需求很繁杂, 只能由人担任.  

我也想加入你们的开源项目.

**Comment by booboosui** [comment]
非常感谢您的认可 也欢迎任何对本项目感兴趣的伙伴加入共建，您可以添加我们的联系方式进一步沟通哈：https://github.com/kuafuai/DevOpsGPT/blob/master/docs/CONTACT.md

**Comment by booboosui** [comment]
@ybeetle8 您添加我wx了吗？
