### ISSUE TITLE
[WinError 2] 系统找不到指定的文件。 后端服务返回异常，请联系管理员检查终端服务日志以及浏览器控制台报错信息。这个是什么情况

### ISSUE THREAD

**Issue by Summercuisine** [kuafuai/DevOpsGPT#50]
[WinError 2] 系统找不到指定的文件。
后端服务返回异常，请联系管理员检查终端服务日志以及浏览器控制台报错信息。
什么情况求告知怎么解决

**Comment by booboosui** [comment]
检查终端服务日志以及浏览器控制台报错信息，可以把信息发出来看看

**Comment by booboosui** [comment]
如果还有问题可以添加我们进一步沟通：https://github.com/kuafuai/DevOpsGPT/blob/master/docs/CONTACT.md
