### ISSUE TITLE
Help with Backend host config

### ISSUE THREAD

**Issue by businistry** [kuafuai/DevOpsGPT#53]
Is any one able to help me with my env.yaml file? I keep getting an error saying "failed to read backend config......" What am I missing?

C:\Users\Todd\Desktop\DevOpsGPT\backend>python run.py
←[91mError: Failed to read the BACKEND_HOST configuration, please 【copy a new env.yaml from env.yaml.tpl】 and reconfigure it according to the documentation. ←[0m
[env - Copy.txt](https://github.com/kuafuai/DevOpsGPT/files/12329078/env.-.Copy.txt)

**Comment by booboosui** [comment]
Looks like a configuration file path problem, try

C:\Users\Todd\Desktop\DevOpsGPT

python backend/run.py

**Comment by He1sinki** [comment]
I had the same problem and changed BACKEND_HOST: '0.0.0.0' to BACKEND_HOST: 'localhost' and now it works for me.
