### ISSUE TITLE
这是还需要配置代理吗

### ISSUE THREAD

**Issue by WJin123456789** [kuafuai/DevOpsGPT#63]
![image](https://github.com/kuafuai/DevOpsGPT/assets/127401398/15015b14-e8d8-4447-ae3f-366777c0dfe8)
![image](https://github.com/kuafuai/DevOpsGPT/assets/127401398/25ce7121-1b2c-48c1-81b2-3a8f158cf4ee)
![image](https://github.com/kuafuai/DevOpsGPT/assets/127401398/dd1607e6-c167-4acf-8a12-af851ea0fcb7)

**Comment by booboosui** [comment]
需要的，但是你这个报错还没到那一步，你访问的URL是 127.0.0.1:8080 么？

**Comment by WJin123456789** [comment]
是的，前端端口是8080，后端端口是8081
![image](https://github.com/kuafuai/DevOpsGPT/assets/127401398/b36e9cc1-187f-4fdb-8808-a35c5a5d16bd)

**Comment by booboosui** [comment]
加 wx 详细沟通下：https://github.com/kuafuai/DevOpsGPT/blob/master/docs/CONTACT.md

**Comment by WJin123456789** [comment]
好的

**Comment by booboosui** [comment]
存在跨域问题，需要访问：127.0.0.1:8080

**Comment by huhy-uniplore** [comment]
请问一下这个问题解决了吗？我也遇到了这个问题。

**Comment by WJin123456789** [comment]
用127.0.0.1:8080访问试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月1日(星期三) 中午12:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63)





 
请问一下这个问题解决了吗？我也遇到了这个问题。

**Comment by huhy-uniplore** [comment]
> 用127.0.0.1:8080访问试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月1日(星期三) 中午12:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 请问一下这个问题解决了吗？我也遇到了这个问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

在运行run.bat就出现这个问题：
000
错误: 不支持输入重新定向，立即退出此进程。
环境变量 HTTP_PROXY  没有定义
环境变量 HTTPS_PROXY  没有定义
环境变量 ALL_PROXY  没有定义
环境变量 http_proxy  没有定义
环境变量 https_proxy  没有定义
环境变量 all_proxy  没有定义

Process finished with exit code -1

相当于还没有跑起来，根本访问不了。

**Comment by WJin123456789** [comment]
你可以把你的问题提交到issue ，我是加了他微信，我那时是改了端口就成功了，你之前修改对应的配置吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月1日(星期三) 下午2:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63)





  
用127.0.0.1:8080访问试试
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月1日(星期三) 中午12:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 请问一下这个问题解决了吗？我也遇到了这个问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
在运行run.bat就出现这个问题：
 000
 错误: 不支持输入重新定向，立即退出此进程。
 环境变量 HTTP_PROXY  没有定义
 环境变量 HTTPS_PROXY  没有定义
 环境变量 ALL_PROXY  没有定义
 环境变量 http_proxy  没有定义
 环境变量 https_proxy  没有定义
 环境变量 all_proxy  没有定义
 
Process finished with exit code -1
 
相当于还没有跑起来，根本访问不了。

**Comment by huhy-uniplore** [comment]
> 你可以把你的问题提交到issue ，我是加了他微信，我那时是改了端口就成功了，你之前修改对应的配置吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月1日(星期三) 下午2:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 用127.0.0.1:8080访问试试 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月1日(星期三) 中午12:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 请问一下这个问题解决了吗？我也遇到了这个问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 在运行run.bat就出现这个问题： 000 错误: 不支持输入重新定向，立即退出此进程。 环境变量 HTTP_PROXY 没有定义 环境变量 HTTPS_PROXY 没有定义 环境变量 ALL_PROXY 没有定义 环境变量 http_proxy 没有定义 环境变量 https_proxy 没有定义 环境变量 all_proxy 没有定义 Process finished with exit code -1 相当于还没有跑起来，根本访问不了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问一下您修改的是env.yaml.中的哪一行的的值呢？

**Comment by WJin123456789** [comment]
我忘记了，改了还是没改，要是要改他应该会有说明叫你改的env.yaml 这个配置文件，你看看他的描述，有没有需要你修改的地方，有的化，你对应的改就ok，我本地已经删除连接这个东西，找不到了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月1日(星期三) 下午2:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63)





  
你可以把你的问题提交到issue ，我是加了他微信，我那时是改了端口就成功了，你之前修改对应的配置吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月1日(星期三) 下午2:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 用127.0.0.1:8080访问试试 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月1日(星期三) 中午12:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 请问一下这个问题解决了吗？我也遇到了这个问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 在运行run.bat就出现这个问题： 000 错误: 不支持输入重新定向，立即退出此进程。 环境变量 HTTP_PROXY 没有定义 环境变量 HTTPS_PROXY 没有定义 环境变量 ALL_PROXY 没有定义 环境变量 http_proxy 没有定义 环境变量 https_proxy 没有定义 环境变量 all_proxy 没有定义 Process finished with exit code -1 相当于还没有跑起来，根本访问不了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
请问一下您修改的是env.yaml.中的哪一行的的值呢？

**Comment by huhy-uniplore** [comment]
> 我忘记了，改了还是没改，要是要改他应该会有说明叫你改的env.yaml 这个配置文件，你看看他的描述，有没有需要你修改的地方，有的化，你对应的改就ok，我本地已经删除连接这个东西，找不到了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月1日(星期三) 下午2:50 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 你可以把你的问题提交到issue ，我是加了他微信，我那时是改了端口就成功了，你之前修改对应的配置吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月1日(星期三) 下午2:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 用127.0.0.1:8080访问试试 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年11月1日(星期三) 中午12:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [kuafuai/DevOpsGPT] 这是还需要配置代理吗 (Issue #63) 请问一下这个问题解决了吗？我也遇到了这个问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 在运行run.bat就出现这个问题： 000 错误: 不支持输入重新定向，立即退出此进程。 环境变量 HTTP_PROXY 没有定义 环境变量 HTTPS_PROXY 没有定义 环境变量 ALL_PROXY 没有定义 环境变量 http_proxy 没有定义 环境变量 https_proxy 没有定义 环境变量 all_proxy 没有定义 Process finished with exit code -1 相当于还没有跑起来，根本访问不了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 请问一下您修改的是env.yaml.中的哪一行的的值呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好的，谢谢
