### ISSUE TITLE
Why mixing YAML and JSON in env file?

### ISSUE THREAD

**Issue by blackshot** [kuafuai/DevOpsGPT#65]
Just that. why not just use one of them?

**Comment by booboosui** [comment]
Thank you for your feedback. We will store part of the configuration in the database in the future

**Comment by booboosui** [comment]
In the latest code, we have stored the configuration information of the application in the database, thank you for your suggestion
<img width="1257" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/139328168/ae24a1b7-7364-42a0-a439-f3a36a84f9e3">
