### ISSUE TITLE
Stuck on "Thinking"? 

### ISSUE THREAD

**Issue by theekruger** [kuafuai/DevOpsGPT#68]
I realized I had to keep the initial description really short, got past that problem, but now part way through it, it just freezes and says thinking? 

What am I doing wrong? lol. Someone please help me, and tell me what I gotta do to be more helpable, is there a log file somewhere I should send?

**Comment by booboosui** [comment]
Can your terminal access the openai web address normally? 

To test the network connectivity, run the ```curl -v https://api.openai.com command```
