### ISSUE TITLE
Network request exception. 后端服务返回异常，请联系管理员检查终端服务日志以及浏览器控制台报错信息。

### ISSUE THREAD

**Issue by Lufffya** [kuafuai/DevOpsGPT#76]
![image](https://github.com/kuafuai/DevOpsGPT/assets/49063302/bbfd4d4a-3cbe-4c47-8273-8752e6d358e6)

我按照教程随手测试了一个例子就报错了，难道作者没测试过吗

**Comment by booboosui** [comment]
看下python报错日志

**Comment by Lufffya** [comment]
@booboosui 后台并没有看到抛出的错误，你说的是哪个日志？

![image](https://github.com/kuafuai/DevOpsGPT/assets/49063302/fe33c81d-4723-474f-a94f-584ab630609a)

**Comment by booboosui** [comment]
服务启动后会有一个python的窗口，里面会显示日志

**Comment by alexdandrei** [comment]
im having kind of the same issue as far as i can tell.

![image_2023-08-27_004209529](https://github.com/kuafuai/DevOpsGPT/assets/7278694/aa39fed5-e4d0-4b4a-bcbe-21948a7d5475)



> 服务启动后会有一个python的窗口，里面会显示日志

im guessing you're referring to this.
![image](https://github.com/kuafuai/DevOpsGPT/assets/7278694/f061b696-d842-4b66-918f-d4bd71b36c00)

**Comment by booboosui** [comment]
> im having kind of the same issue as far as i can tell.
> 
> > 服务启动后会有一个python的窗口，里面会显示日志
> 
> im guessing you're referring to this. ![image](https://user-images.githubusercontent.com/7278694/263514773-f061b696-d842-4b66-918f-d4bd71b36c00.png)

This error should not affect service operation, is the access to http://127.0.0.1:8080 normal?

**Comment by alexdandrei** [comment]
> This error should not affect service operation, is the access to http://127.0.0.1:8080 normal?

Not really. The server spins up eventually, and i get the same errors from the guy above: 
`'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.
000
'http_proxy' is not recognized as an internal or external command,
operable program or batch file.
'https_proxy' is not recognized as an internal or external command,
operable program or batch file.
'all_proxy' is not recognized as an internal or external command,
operable program or batch file.`

eventually it will spin up the server 
`Serving HTTP on :: port 8080 (http://[::]:8080/) ...` (no ip there, just [::]) 

So i open http://127.0.0.1:8080/ and it looks like it's not communication with the backend.

![image](https://github.com/kuafuai/DevOpsGPT/assets/7278694/8880bbd0-237c-4741-937b-7cf6d1fd07c7)

**Comment by alexdandrei** [comment]
Also: there were errors about HTTP_PROXY, HTTPS_PROXY, ALL_PROXY variable missing, so i set them up in windows environment variables with ip 127.0.0.1:8080

**Comment by booboosui** [comment]
> ALL_PROXY

Is there any error message in the browser console?

<img width="1535" alt="image" src="https://github.com/kuafuai/DevOpsGPT/assets/139328168/36ab51d9-3f54-4ae8-b348-65832e2ac63e">

**Comment by yakeJiang** [comment]
> im having kind of the same issue as far as i can tell.
> 
> > 服务启动后会有一个python的窗口，里面会显示日志
> 
> im guessing you're referring to this. ![image](https://user-images.githubusercontent.com/7278694/263514773-f061b696-d842-4b66-918f-d4bd71b36c00.png)

hi , you can see local flask version . or you can  update watchdog
you can try :
pip install --upgrade watchdog

**Comment by alexdandrei** [comment]
> > ALL_PROXY
> 
> Is there any error message in the browser console?

There used to be... CONNECTION_REFUSED i think it was, but @yakeJiang cracked it. it was watchdogs version to blame.

Thank you.
