### ISSUE TITLE
Local variable e

### ISSUE THREAD

**Issue by businistry** [kuafuai/DevOpsGPT#77]
I keep getting this error about a local variable e. But its not defined anywhere in the code. Here are my logs. 
[variable e.txt](https://github.com/kuafuai/DevOpsGPT/files/12435115/variable.e.txt)

**Comment by booboosui** [comment]
Follow this document to check the contents of configuring Git and CI：https://github.com/kuafuai/DevOpsGPT/blob/master/docs/DOCUMENT.md

**Comment by businistry** [comment]
do i edit that somewhere here: 

APPS: |
  [
    {
        "id": 3,
        "name": "Demo applications that support any development needs（支持任何开发需求的演示应用）",
        "intro": "Demo applications that support any development needs, You can submit any development requirements.",
        "default_source_branch": "master",
        "default_target_branch": "dev",
        "service": [
            {
                "name": "toddc",
                "git_path": "businistry/app",
                "git_workflow": "default.yaml",
                "docker_image": "docker.io/kuafuai/template-freestyleapp:latest",
                "docker_group": "devopsgtp-test",
                "docker_name": "free-demo",
                "base_prompt": "You can choose any appropriate development language",
                "intro": "service name: free_demo\nrole of service: used to develop any requirements\ndevelopment language: no limit\ndevelopment framework: no limit",
                "api_doc_url": "",
                "api_doc": "",
                "struct": "This is a new service, no limits",
                "lib": "no limit",
                "specification": {
                    "Default": "- You can choose any appropriate development language"
                }
            }
        ]

Im sorry, im really new to this and this isnt that clear to me.

**Comment by booboosui** [comment]
Usually you need to modify the following configuration
```
DEVOPS_TOOLS: "github" 
GIT_ENABLED: true  
GIT_URL: "https://github.com"  
GIT_API: "https://api.github.com" 
GIT_TOKEN: "ghp_xxxx"   # Get from here https://github.com/settings/tokens
GIT_USERNAME: "booboosui"
GIT_EMAIL: "suixiaobo@kuafuai.net"
```
