### ISSUE TITLE
docker depoly

### ISSUE THREAD

**Issue by av8dtop** [kuafuai/DevOpsGPT#79]
我發現這好像是國內鏡像
是否能改成國外或者過內

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f091fb04400>, 'Connection to pypi.tuna.tsinghua.edu.cn timed out. (connect timeout=15)')': /simple/flask-sqlalchemy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/flask-sqlalchemy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/flask-sqlalchemy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/flask-sqlalchemy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/flask-sqlalchemy/
ERROR: Could not find a version that satisfies the requirement flask-sqlalchemy (from versions: none)
ERROR: No matching distribution found for flask-sqlalchemy

**Comment by booboosui** [comment]
你在本地可以訪問到這個域名嗎？執行：```curl -v https://pypi.tuna.tsinghua.edu.cn```

**Comment by av8dtop** [comment]
> 你在本地可以訪問到這個域名嗎？執行：`curl -v https://pypi.tuna.tsinghua.edu.cn`

沒辦法
我現在用git編譯直接把這段拿掉沒問題
但是我習慣用docker了
到時候看板主是否有更好的做法可以處理
或者寫一個docker compose 做編譯再run
感謝你的回答

**Comment by booboosui** [comment]
可以使用最新的鏡像試一下，已經在構建過程中將依賴拉取到鏡像中
