### ISSUE TITLE
編輯應用列表有BUG

### ISSUE THREAD

**Issue by av8dtop** [kuafuai/DevOpsGPT#80]
newService = ApplicationService.create_service(appID, service["service_name"], service["service_git_path"], service["service_workflow"], service["service_role"], service["service_language"], service["service_framework"], service["service_database"], service["service_api_type"], service["service_api_location"], service["service_container_name"], service["service_container_group"], service["service_region"], service["service_public_ip"], service["service_security_group"], service["service_cd_subnet"], service["service_struct_cache"])
KeyError: 'service_name'

會變成創建新的
但是我只是要修改

**Comment by wangchangjiu** [comment]
![image](https://github.com/kuafuai/DevOpsGPT/assets/25260012/1fe91c4d-0507-4538-b6af-343be0047655)

**Comment by booboosui** [comment]
This issue has been fixed in the latest version, thank you for your feedback #95
