### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by dongguacc10** [kuafuai/DevOpsGPT#9]
![image](https://github.com/kuafuai/DevOpsGPT/assets/139732219/cd42bb52-608d-43f4-87ff-c0d6302be2c5)

**Comment by booboosui** [comment]
麻烦提供一下完整的日志

**Comment by dongguacc10** [comment]
> 麻烦提供一下完整的日志

就是一直重复 service has not startedyet。唯一报警的就是红色部分。上面的正常的。

**Comment by booboosui** [comment]
直接用cmd，运行 python3 backend\run.py  看看，（python3 根据你的实际情况调整，比如 python3.11）

**Comment by booboosui** [comment]
如果您还有问题，可以添加我们助手进行沟通：https://github.com/kuafuai/DevOpsGPT/blob/master/docs/CONTACT.md
